apiVersion: v2
name: platform-stack
version: 1.0.0
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: 11.1.3
    repository: https://charts.bitnami.com/bitnami
    alias: messaging