apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: migrate/migrate:latest
        command: ["migrate"]
        args:
        - "-path=/migrations"
        - "-database=postgres://$(DB_HOST)/$(DB_NAME)?sslmode=require"
        - "up"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: database