# gitops/apps/user-service-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/org/app-teams.git'
    targetRevision: main  # Watches main branch
    path: services/user-service/k8s/overlays/production
    # ArgoCD automatically picks up the new image tag from kustomization.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: user-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true  # Only sync when changes detected