# argocd-admin-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  
  target:
    name: argocd-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
      type: Opaque
      data:
        # ArgoCD expects bcrypt hash for admin password
        admin.password: "{{ .bcrypt }}"
        admin.passwordMtime: "{{ now | date "2006-01-02T15:04:05Z" }}"
        # Server signature key for JWT tokens
        server.secretkey: "{{ .jwt_secret }}"
  
  data:
  - secretKey: bcrypt
    remoteRef:
      key: production/argocd/admin/password
      property: bcrypt
  - secretKey: jwt_secret
    remoteRef:
      key: production/argocd/admin/password
      property: jwt_secret