# argocd-oidc-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        oidc.aws.clientSecret: "{{ .client_secret }}"
        oidc.gitlab.clientSecret: "{{ .gitlab_client_secret }}"
        webhook.github.secret: "{{ .github_webhook_secret }}"
  
  data:
  - secretKey: client_secret
    remoteRef:
      key: production/argocd/auth/oidc
      property: client_secret
  - secretKey: gitlab_client_secret
    remoteRef:
      key: production/argocd/auth/gitlab
      property: client_secret
  - secretKey: github_webhook_secret
    remoteRef:
      key: production/argocd/webhooks/github
      property: secret

---
# ArgoCD ConfigMap with OIDC configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # OIDC configuration
  oidc.config: |
    name: AWS SSO
    issuer: https://portal.sso.us-west-2.amazonaws.com
    clientId: d58c10e4-1234-5678-9abc-def123456789
    clientSecret: $oidc.aws.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  
  # GitLab integration
  dex.config: |
    connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://gitlab.company.com
        clientID: argocd-gitlab-app
        clientSecret: $oidc.gitlab.clientSecret
        redirectURI: https://argocd.company.com/api/dex/callback
        groups:
        - argocd-admins
        - argocd-developers
        useLoginAsID: false
  
  # URL configuration
  url: https://argocd.company.com
  
  # RBAC configuration
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, applications, action/*, */*, allow
    g, argocd-admins, role:admin
    g, argocd-developers, role:developer