apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: "my-thanos-metrics-bucket"
      endpoint: "s3.amazonaws.com"
      access_key: "YOUR_AWS_ACCESS_KEY"
      secret_key: "YOUR_AWS_SECRET_KEY"
      region: "us-east-1"

# kubectl apply -f thanos-objstore-secret.yaml
