apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-only-binding
subjects:
  - kind: User
    name: "<your-aws-iam-user>"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-read-only # Must match exactly the role name
  apiGroup: rbac.authorization.k8s.io
