apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce # volume can be mounted by one node at a time.
  storageClassName: auto-ebs-sc # Must match storage class
  resources:
    requests:
      storage: 8Gi